-- schema_and_atomic_update.sql
-- Example for SQLite / broadly portable SQL with small tweaks.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed example user (password hash must be generated by backend code)
-- INSERT INTO users (email, password_hash)
-- VALUES ('demo@example.com', '$2b$12$replace_with_real_bcrypt_hash');

-- =========================================================
-- Atomic change-email pattern
-- Inputs expected from backend:
--   :auth_user_id
--   :old_email
--   :new_email
-- The backend must already:
--   1) authenticate the session/token,
--   2) verify password using a strong hash,
--   3) validate email format,
--   4) check new_email != old_email.
-- =========================================================

BEGIN IMMEDIATE TRANSACTION;

-- Optional conflict check
SELECT 1
FROM users
WHERE email = :new_email
  AND id <> :auth_user_id;

-- Atomic compare-and-set update bound to authenticated user id
UPDATE users
SET email = :new_email
WHERE id = :auth_user_id
  AND email = :old_email;

COMMIT;

-- The backend should verify:
--   affected_rows = 1  => success
--   affected_rows = 0  => reject / conflict / stale old email

-- =========================================================
-- Useful read query for backend
-- =========================================================
-- SELECT id, email, password_hash FROM users WHERE id = :auth_user_id;

-- =========================================================
-- Example rejected cases handled by backend before SQL:
-- - wrong password
-- - invalid email format
-- - same email
-- =========================================================