-- PostgreSQL schema

CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ux_users_email ON users(email);

-- Example password hashes should be generated by app code using bcrypt/argon2.
-- Never store plain passwords.

-- Atomic pattern used by app code:
-- 1) BEGIN
-- 2) SELECT ... FOR UPDATE to lock the authenticated user's row
-- 3) verify password in app
-- 4) UPDATE email
-- 5) COMMIT

BEGIN;

SELECT id, email, password_hash
FROM users
WHERE id = $1
FOR UPDATE;

-- App checks:
-- - row exists
-- - email matches oldEmail for current authenticated user
-- - password hash verifies
-- - newEmail != oldEmail

UPDATE users
SET email = $2,
    updated_at = NOW()
WHERE id = $1;

COMMIT;