-- change_email.sql
--
-- PostgreSQL example
-- Purpose:
--   Safe database-side support for a login/session-backed email change flow.
--   The application must first verify that the user is logged in and pass the
--   authenticated user id into this function.
--
-- What this SQL does:
-- - Stores users
-- - Keeps passwords hashed (application should create the hash)
-- - Atomically updates email only when:
--     1) session user id matches the row being changed
--     2) old email matches current email
--     3) new email is different
-- - Returns generic success/failure signals
--
-- Important:
-- - Password verification should normally be done in the application layer
--   using a modern password hashing library such as bcrypt/argon2.
-- - This function assumes the app already authenticated the user and verified
--   the password before calling it.

BEGIN;

CREATE TABLE IF NOT EXISTS app_users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Example seed row; use a real hash generated by your app, not plain text.
-- Password hash below is only a placeholder format example.
INSERT INTO app_users (email, password_hash)
VALUES ('user@example.com', '$2b$12$exampleplaceholderhashvaluegoeshere..............')
ON CONFLICT (email) DO NOTHING;

CREATE OR REPLACE FUNCTION change_user_email(
    p_session_user_id BIGINT,
    p_old_email VARCHAR,
    p_new_email VARCHAR
)
RETURNS TABLE(success BOOLEAN, message TEXT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_updated_rows INT;
BEGIN
    -- Basic validation
    IF p_session_user_id IS NULL THEN
        RETURN QUERY SELECT FALSE, 'Unauthorized.';
        RETURN;
    END IF;

    IF p_old_email IS NULL OR p_new_email IS NULL THEN
        RETURN QUERY SELECT FALSE, 'Invalid input.';
        RETURN;
    END IF;

    p_old_email := lower(trim(p_old_email));
    p_new_email := lower(trim(p_new_email));

    IF p_old_email = '' OR p_new_email = '' THEN
        RETURN QUERY SELECT FALSE, 'Invalid input.';
        RETURN;
    END IF;

    IF p_old_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
       OR p_new_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' THEN
        RETURN QUERY SELECT FALSE, 'Invalid input.';
        RETURN;
    END IF;

    IF p_old_email = p_new_email THEN
        RETURN QUERY SELECT FALSE, 'New email must be different.';
        RETURN;
    END IF;

    -- Prevent duplicate target email
    IF EXISTS (
        SELECT 1
        FROM app_users
        WHERE email = p_new_email
          AND id <> p_session_user_id
    ) THEN
        RETURN QUERY SELECT FALSE, 'Unable to update email.';
        RETURN;
    END IF;

    -- Atomic conditional update:
    -- only updates the authenticated user's row if old email still matches
    UPDATE app_users
    SET email = p_new_email
    WHERE id = p_session_user_id
      AND email = p_old_email;

    GET DIAGNOSTICS v_updated_rows = ROW_COUNT;

    IF v_updated_rows = 1 THEN
        RETURN QUERY SELECT TRUE, 'Email updated successfully.';
    ELSE
        RETURN QUERY SELECT FALSE, 'Unable to update email.';
    END IF;
END;
$$;

COMMIT;

-- Example usage from the application after session + password verification:
-- SELECT * FROM change_user_email(1, 'user@example.com', 'newuser@example.com');