-- app.sql
-- PostgreSQL-style database layer for secure login/email update logic.
-- Note: SQL alone does not implement the web session/UI. Your backend should:
--   1) authenticate the user,
--   2) obtain authenticated_user_id from session/token,
--   3) pass oldEmail, newEmail, and verified password input here.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Example seed row (hash should be generated by backend, not hardcoded in real deployment)
-- INSERT INTO users (email, password_hash)
-- VALUES ('user@example.com', '$2b$12$replace_with_real_bcrypt_hash');

COMMIT;

-- Secure email change function:
-- - authenticated_user_id comes from server-side session, not user input trust
-- - old email must match current account email
-- - password hash must match exactly as verified by DB-supported crypt/bcrypt
-- - new email must be valid and different
-- - failure message is generic
--
-- Requires pgcrypto extension if using crypt():
--   CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION change_user_email(
    p_authenticated_user_id BIGINT,
    p_old_email VARCHAR,
    p_new_email VARCHAR,
    p_password_plain TEXT
)
RETURNS TABLE(success BOOLEAN, message TEXT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_email VARCHAR(254);
    v_password_hash TEXT;
    v_exists BIGINT;
    v_rows INT;
BEGIN
    -- Basic input validation
    IF p_authenticated_user_id IS NULL THEN
        RETURN QUERY SELECT FALSE, 'Unauthorized';
        RETURN;
    END IF;

    p_old_email := lower(trim(p_old_email));
    p_new_email := lower(trim(p_new_email));

    IF p_old_email IS NULL OR p_new_email IS NULL OR p_password_plain IS NULL THEN
        RETURN QUERY SELECT FALSE, 'Invalid input';
        RETURN;
    END IF;

    IF length(p_old_email) = 0 OR length(p_new_email) = 0 OR length(p_password_plain) = 0 THEN
        RETURN QUERY SELECT FALSE, 'Invalid input';
        RETURN;
    END IF;

    IF p_new_email = p_old_email THEN
        RETURN QUERY SELECT FALSE, 'New email must be different';
        RETURN;
    END IF;

    IF p_old_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
       OR p_new_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' THEN
        RETURN QUERY SELECT FALSE, 'Invalid input';
        RETURN;
    END IF;

    -- Lock the authenticated user's row
    SELECT email, password_hash
      INTO v_current_email, v_password_hash
      FROM users
     WHERE id = p_authenticated_user_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RETURN QUERY SELECT FALSE, 'Unauthorized';
        RETURN;
    END IF;

    -- Verify old email matches logged-in user
    IF v_current_email <> p_old_email THEN
        RETURN QUERY SELECT FALSE, 'Email change failed';
        RETURN;
    END IF;

    -- Verify password against stored bcrypt hash
    IF v_password_hash <> crypt(p_password_plain, v_password_hash) THEN
        RETURN QUERY SELECT FALSE, 'Email change failed';
        RETURN;
    END IF;

    -- Prevent reuse/conflict
    SELECT id INTO v_exists
      FROM users
     WHERE email = p_new_email
       AND id <> p_authenticated_user_id
     LIMIT 1;

    IF v_exists IS NOT NULL THEN
        RETURN QUERY SELECT FALSE, 'Email change failed';
        RETURN;
    END IF;

    UPDATE users
       SET email = p_new_email
     WHERE id = p_authenticated_user_id
       AND email = p_old_email;

    GET DIAGNOSTICS v_rows = ROW_COUNT;

    IF v_rows <> 1 THEN
        RETURN QUERY SELECT FALSE, 'Email change failed';
        RETURN;
    END IF;

    RETURN QUERY SELECT TRUE, 'Email updated successfully';
END;
$$;

-- Example usage from backend:
-- SELECT * FROM change_user_email(1, 'user@example.com', 'new@example.com', 'StrongPassword123!');